DEFAULT_HOME = 'Music'
QUERY_APPEND = ' "Auto-generated by YouTube."'

import time
import flask
import pytube
import youtubesearchpython as ysp

app = flask.Flask(__name__, static_url_path='/')

def is_using_client():
    flask.request.headers.get('User-Agent') != 'MUSE Client'

@app.route('/')
def home():
    return flask.redirect(f'/search?q={DEFAULT_HOME.replace(" ", "+")}&view=grid')

@app.route('/search')
def search():
    query = flask.request.args.get('q')
    title = f'{query} · MUSE Search'

    results = ysp.VideosSearch(query + QUERY_APPEND, limit=10).result()['result']
    
    if query == DEFAULT_HOME:
        title = 'Home · MUSE'
        query = ''

    return flask.render_template('index.html', title=title, query=query, results=results, view=flask.request.args.get('view') or 'list')

@app.route('/watch')
def watch():
    video_id = flask.request.args.get('v')

    fetcher = ysp.StreamURLFetcher()
    video = ysp.Video.get(video_id)
    data = ysp.Video.getInfo(video_id)
    url = fetcher.get(video, 251)
    
    return flask.render_template('player.html', url=url, data=data)

app.run(port=2244, debug=True)