DEFAULT_HOME = 'Music'
QUERY_APPEND = ' "Auto-generated by YouTube."'

import time
import flask
import pytube
import azlyrics.azlyrics
import youtubesearchpython as ysp

app = flask.Flask(__name__, static_url_path='/')

def is_using_client():
    flask.request.headers.get('User-Agent') != 'MUSE Client'

def get_lyrics(artist: str, title: str):
    print(artist, title)

    # lyrics = azlyrics.azlyrics.lyrics(artist, title)[0].split('\n')
    return '' #lyrics

@app.route('/')
def home():
    return flask.redirect(f'/search?q={DEFAULT_HOME.replace(" ", "+")}&view=grid')

def search_redirect(video_id):
    flask.redirect(f'/watch?v={video_id}')

@app.route('/search')
def search():
    query = flask.request.args.get('q')

    results = ysp.VideosSearch(query + QUERY_APPEND, limit=10).result()['result']
    title = f'{query} · MUSE Search'
    
    if query == DEFAULT_HOME:
        title = 'Home · MUSE'
        query = ''

    return flask.render_template('index.html', title=title, query=query, results=results, view=flask.request.args.get('view') or 'list')

@app.route('/watch')
def watch():
    video_id = flask.request.args.get('v')

    fetcher = ysp.StreamURLFetcher()
    video = ysp.Video.get(video_id)
    data = ysp.Video.getInfo(video_id)
    url = fetcher.get(video, 251)

    channel = data['channel']['name']

    artist = channel
    if ' - Topic' in channel:
        artist = data['channel']['name'].split(' - Topic')[0]

    return flask.render_template('player.html', url=url, data=data, lyrics=get_lyrics(artist, data['title']), views=data['viewCount']['text'], descriptions=data['description'])

app.run(port=2244, debug=True)
